### ISSUE TITLE
search not working ?

### ISSUE THREAD

**Issue by koenhandekyn** [TrestleAdmin/trestle-search#5]
this is not working (nothing filtered) 

```
  collection do
    Customer.order(name: :asc)
  end

  search do |q|
    # puts "test" # when adding debugging statements this doesn't seem to be called
    collection.where("name LIKE ?", "%#{q}%")
  end
```

while this is actually doing the filter (if manually adding the q param)

```
  collection do
    Customer.order(name: :asc).where("name LIKE ?", "%#{params[:q]}%")
  end
```

the infrastructure recognises the presence of the search block as a search input is shown. but i've added some debugging statement in the search block and it doesn't seem to be called ?

**Comment by spohlenz** [comment]
I should have released a new version of `trestle-search` after releasing Trestle 0.8.11.

This has now been rectified with the 0.3.0 release of `trestle-search.

**Comment by koenhandekyn** [comment]
it's working !
