### ISSUE TITLE
Search on author of a post/book

### ISSUE THREAD

**Issue by rkumar** [TrestleAdmin/trestle-search#51]
I have a book/post table with author_id linking to author table (belongs_to :author). 
I am trying to add the author's name in the search but I keep getting errors because it seems that the author table is not getting linked in the query.

I've tried to add the authors table as follows:
```
  collection do
    # Set the default order when manual sorting is not applied
    Book.order(created_at: :desc).includes(:author)
  end
  collection do
    model.includes(:author)
  end

```

I've also tried to add in the author in the search query:

```
  search do |query|
    query ? collection.joins(:author).where("author.name ILIKE ?", "%#{query}%" ) : collection
  end

```

However I keep getting errors such as:

```
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "author"
LINE 1: ...s" ON "authors"."id" = "books"."author_id" WHERE (author.nam...
```

How can I perform a search on a linked table ?

**Comment by spohlenz** [comment]
The where clause needs to refer to the actual table name rather than the association, so it should be pluralized:

```ruby
collection.joins(:author).where("authors.name ILIKE ?", "%#{query}%")
```

**Comment by rkumar** [comment]
Thanks. Worked perfectly.
