### ISSUE TITLE
Sorting on a calculated field

### ISSUE THREAD

**Issue by rkumar** [TrestleAdmin/trestle-search#52]
My listing of authors has a book count column. I'd like to be to sort on that. I am trying:

```
    column :books , sort: :books_count  do |auth|
       auth.books.count
    end
```

I've tried to set it up as follows:

 ```
 collection do
    # Set the default order when manual sorting is not applied
    Author.order(created_at: :desc).includes(:books)
  end
  collection do
    model.includes(:books)
  end

  sort_column :books_count do |collection, order|
    collection.joins(:books).merge(Book.order(count: order))
  end
```
However, I am just not able to get the sort_column part correct.

**Comment by spohlenz** [comment]
Try this:

```ruby
sort_column :books_count do |collection, order|
  collection.left_joins(:books).group(:id).reorder("COUNT(books.id) #{order}")
end
```

**Comment by rkumar** [comment]
My second query is regarding default sort order of the table in index view. I notice that the last updated row falls to the bottom/end. I'd like it to be at the top. 

I've tried:

```
  collection do
    # Set the default order when manual sorting is not applied
    Author.order(updated_at: :desc).includes(:books)
  end
```

and 

`  scope :ordered, -> { order(id: :desc) }
`

None of the above, seems to have any effect.

**Comment by spohlenz** [comment]
Your `collection` block looks correct -- when you load the page initially without selecting a sort column you should see the latest updated rows at the top.

With scopes, you may need to use `reorder` instead of `order` to override the sort order when a default order is specified.

**Comment by rkumar** [comment]
Thanks. The second `collection` block was overriding the first one which had the order. Now its working. Thanks for the amazingly quick responses.
